# -*- coding: utf-8 -*-
"""ServGo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198NqKdwReo71F4ZngpynANHecD7E2H_R
"""

from dataclasses import dataclass
from datetime import datetime

# Regras de Negócio.
class ErroServGo(Exception): pass
class LoginInvalidoError(ErroServGo): pass
class RegraNegocioError(ErroServGo): pass
class ServicoNaoEncontradoError(ErroServGo): pass

# DTOs - Entidades Periféricas.
@dataclass(frozen=True)
class PessoaDTO:
    cpf: str
    nome: str
    telefone: str
    endereco: str
    data_nascimento: str

@dataclass(frozen=True)
class UsuarioDTO:
    login: str
    senha: str
    email: str

@dataclass(frozen=True)
class ClienteDTO:
    forma_pagamento: str
    status: str
    preferencia_servico: str

@dataclass(frozen=True)
class PrestadorDTO:
    cnpj: str
    servico: str
    valores: float

# Classes Principais - Herança e Polimorfismo.

class Notificavel:
    """notificacao"""
    def notificar(self, msg: str):
        return f"[NOTIFICAÇÃO] {msg}"

class Avaliavel:
    """notificacao"""
    def avaliar_atendimento(self, nota: int):
        return f"Avaliação registrada: {nota}/5 estrelas."

class Pessoa:
    def __init__(self, p_dto: PessoaDTO):
        self.cpf = p_dto.cpf
        self.nome = p_dto.nome
        self.telefone = p_dto.telefone
        self.endereco = p_dto.endereco
        self.data_nascimento = p_dto.data_nascimento

# Polimorfismo.
    def fazer_cadastro(self):
        return f"Cadastro base de {self.nome} realizado."

# Usuário com herança simples.
class Usuario(Pessoa):
    def __init__(self, p_dto: PessoaDTO, u_dto: UsuarioDTO):
        super().__init__(p_dto)
        self.login = u_dto.login
        self.senha = u_dto.senha
        self.email = u_dto.email

    def fazer_cadastro(self):
        return f"Usuário {self.login} criado com sucesso."

    def fazer_login(self):
        return f"Login de {self.login} autenticado."

    def validar_email(self):
        return f"E-mail {self.email} validado com sucesso."

# Usuário com herança de três níveis.
class Cliente(Usuario, Notificavel, Avaliavel):
    def __init__(self, p_dto: PessoaDTO, u_dto: UsuarioDTO, c_dto: ClienteDTO):
        super().__init__(p_dto, u_dto)
        self.forma_pagamento = c_dto.forma_pagamento
        self.status = c_dto.status
        self.preferencia_servico = c_dto.preferencia_servico

    def fazer_cadastro(self):
        return f"[CLIENTE] {self.nome} cadastrado! Status: {self.status}."

    def buscar_servico(self):
        return "Buscando serviços disponíveis..."

    def pagar(self, valor: float):
        return f"Pagamento de R${valor:.2f} via {self.forma_pagamento} confirmado."

# Usuário com herança de três níveis.
class Prestador(Usuario, Notificavel, Avaliavel):
    def __init__(self, p_dto: PessoaDTO, u_dto: UsuarioDTO, pr_dto: PrestadorDTO):
        super().__init__(p_dto, u_dto)
        self.cnpj = pr_dto.cnpj
        self.servico = pr_dto.servico
        self.valores = pr_dto.valores

    def fazer_cadastro(self):
        return f"[PRESTADOR] {self.nome} cadastrado para {self.servico}."

    def receber_e_finalizar_pedido(self):
        return "Trabalho executado e pedido finalizado no sistema."

# Início do sistema principal:

banco_usuarios = []
banco_pedidos = []
usuario_logado = None

def menu():
    global usuario_logado

    while True:
        status = f"[LOGADO: {usuario_logado.nome}]" if usuario_logado else "[DESLOGADO]"
        print(f"\n{'='*10} SERVGO SYSTEM {status} {'='*10}")
        print("1. Cadastrar Usuário.")
        print("2. Fazer Login.")
        print("3. Listar Cadastros.")
        print("4. Criar Novo Pedido.")
        print("5. Buscar Prestadores.")
        print("6. Finalizar Pedido e Avaliar.")
        print("7. Sair / Logout.")

        opcao = input("Escolha uma opção: ")

        match opcao:
            case "1":
                try:
                    print("\n--- Cadastro de Pessoa ---")
                    nome = input("Nome: "); cpf = input("CPF: ")
                    tel = input("Tel: "); end = input("End: "); nasc = input("Nasc: ")

                    print("\n--- Dados de Acesso ---")
                    email = input("Email: "); log = input("Login: "); sen = input("Senha: ")

                    tipo = input("Tipo: (1) Cliente | (2) Prestador: ")

                    p_dto = PessoaDTO(cpf, nome, tel, end, nasc)
                    u_dto = UsuarioDTO(log, sen, email)

                    if tipo == "1":
                        pgto = input("Pagamento (Pix/Cartão): ")
                        pref = input("Preferência de Serviço: ")
                        novo = Cliente(p_dto, u_dto, ClienteDTO(pgto, "Ativo", pref))
                    elif tipo == "2":
                        cnpj = input("CNPJ: "); serv = input("Serviço: ")
                        val = float(input("Valor Base: "))
                        novo = Prestador(p_dto, u_dto, PrestadorDTO(cnpj, serv, val))
                    else:
                        raise RegraNegocioError("Tipo inválido.")

                    banco_usuarios.append(novo)
                    print(novo.fazer_cadastro())
                except Exception as e:
                    print(f"Erro: {e}")

            case "2":
                try:
                    log_in = input("Login: "); sen_in = input("Senha: ")
       # Lista de busca:
                    busca = [u for u in banco_usuarios if u.login == log_in and u.senha == sen_in]
                    if not busca:
                        raise LoginInvalidoError("Login ou senha incorretos.")
                except LoginInvalidoError as e:
                    print(f"❌ {e}")
                else:
                    usuario_logado = busca[0]
                    print(f"✅ {usuario_logado.fazer_login()}")
                finally:
                    print("-" * 30)

            case "3":
                print("\n--- LISTA DE USUÁRIOS ---")
                for u in banco_usuarios:
                    print(u.fazer_cadastro())

            case "4":
                try:
                    if not isinstance(usuario_logado, Cliente):
                        raise RegraNegocioError("Apenas clientes podem criar pedidos.")

                    desc = input("Descrição do serviço: ")
                    val = float(input("Valor ofertado: "))

        # Pedido como dicionário:
                    pedido = {
                        "id": len(banco_pedidos) + 1,
                        "valor": val,
                        "descricao": desc,
                        "data": datetime.now().strftime("%d/%m/%Y"),
                        "cliente": usuario_logado.nome
                    }
                    banco_pedidos.append(pedido)
                    print(f"✅ Pedido #{pedido['id']} registrado!")
                except Exception as e:
                    print(f"Erro: {e}")

            case "5":
                termo = input("Buscar por qual serviço? ").lower()
        # Lista para filtros:
                encontrados = [u for u in banco_usuarios if isinstance(u, Prestador) and termo in u.servico.lower()]
                if encontrados:
                    for p in encontrados:
                        print(f"Prestador: {p.nome} | Serviço: {p.servico} | Valor: R${p.valores}")
                else:
                    print("Nenhum prestador encontrado.")

            case "6":
                try:
                    if not usuario_logado: raise RegraNegocioError("Faça login.")

                    id_p = int(input("ID do pedido: "))
                    busca_p = [p for p in banco_pedidos if p['id'] == id_p]
                    if not busca_p: raise RegraNegocioError("Pedido não existe.")

                    pedido = busca_p[0]
                    nome_pr = input("Nome do prestador que realizou o serviço: ")

        # Localizando objetos para Notificação e Avaliação:
                    pr_obj = next((u for u in banco_usuarios if isinstance(u, Prestador) and u.nome == nome_pr), None)
                    cl_obj = next((u for u in banco_usuarios if isinstance(u, Cliente) and u.nome == pedido['cliente']), None)

                    if not pr_obj: raise RegraNegocioError("Prestador não encontrado.")

        # Finalização:
                    print(cl_obj.notificar(f"Serviço '{pedido['descricao']}' concluído!"))
                    print(pr_obj.notificar(f"Pagamento de R${pedido['valor']} recebido."))
                    print(pr_obj.receber_e_finalizar_pedido())

                    print("\n--- AVALIAÇÕES ---")
                    nota_p = int(input(f"Nota para o prestador {pr_obj.nome} (1-5): "))
                    print(cl_obj.avaliar_atendimento(nota_p))

                    banco_pedidos.remove(pedido)
                except Exception as e:
                    print(f"Erro: {e}")

            case "7":
                if usuario_logado:
                    print(f"Logout de {usuario_logado.nome}..."); usuario_logado = None
                else:
                    print("Saindo..."); break
            case _:
                print("Opção inválida.")

if __name__ == "__main__":
    menu()
